---
language: csharp

mono:
  - 4.4.2
  - 4.6.1
  - weekly
  - latest

before_install:
   - rvm install 2.2.3

install:
  - gem install bundler
  - bundle

script:
  - bundle exec rake DEBUG=true

matrix:
  allow_failures:
   - mono: latest
   - mono: weekly
   - mono: 4.4.2

env:
  global:
    - TMPDIR=/tmp
